"""empty message

Revision ID: 09149bfebb67
Revises: 0cb6c9d67eee
Create Date: 2020-02-02 23:46:39.434287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09149bfebb67'
down_revision = '0cb6c9d67eee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
