"""empty message

Revision ID: 0ac4fd426bfc
Revises: 035fbc8b3004
Create Date: 2020-02-15 21:55:32.642115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ac4fd426bfc'
down_revision = '035fbc8b3004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('contact_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Artist', 'ContactInfo', ['contact_id'], ['id'])
    op.drop_column('Artist', 'phone')
    op.drop_column('Artist', 'state')
    op.drop_column('Artist', 'city')
    op.drop_column('Artist', 'facebook_link')
    op.add_column('ContactInfo', sa.Column('address', sa.String(length=120), nullable=True))
    op.add_column('ContactInfo', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('ContactInfo', sa.Column('facebook_link', sa.String(length=120), nullable=True))
    op.add_column('ContactInfo', sa.Column('phone', sa.String(length=120), nullable=True))
    op.add_column('ContactInfo', sa.Column('state', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('contact_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Venue', 'ContactInfo', ['contact_id'], ['id'])
    op.drop_column('Venue', 'address')
    op.drop_column('Venue', 'state')
    op.drop_column('Venue', 'phone')
    op.drop_column('Venue', 'facebook_link')
    op.drop_column('Venue', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('facebook_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'contact_id')
    op.drop_column('ContactInfo', 'state')
    op.drop_column('ContactInfo', 'phone')
    op.drop_column('ContactInfo', 'facebook_link')
    op.drop_column('ContactInfo', 'city')
    op.drop_column('ContactInfo', 'address')
    op.add_column('Artist', sa.Column('facebook_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Artist', type_='foreignkey')
    op.drop_column('Artist', 'contact_id')
    # ### end Alembic commands ###
