"""empty message

Revision ID: 490796f312a9
Revises: 577013d54038
Create Date: 2020-02-23 19:52:34.330762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490796f312a9'
down_revision = '577013d54038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ContactInfo', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ContactInfo', 'website')
    # ### end Alembic commands ###
