"""empty message

Revision ID: 577013d54038
Revises: 0ac4fd426bfc
Create Date: 2020-02-15 21:58:08.092906

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '577013d54038'
down_revision = '0ac4fd426bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Artist', 'ContactInfo', ['contact_id'], ['id'])
    op.drop_column('Artist', 'city')
    op.drop_column('Artist', 'state')
    op.drop_column('Artist', 'facebook_link')
    op.drop_column('Artist', 'phone')
    op.add_column('ContactInfo', sa.Column('address', sa.String(length=120), nullable=True))
    op.add_column('ContactInfo', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('ContactInfo', sa.Column('facebook_link', sa.String(length=120), nullable=True))
    op.add_column('ContactInfo', sa.Column('phone', sa.String(length=120), nullable=True))
    op.add_column('ContactInfo', sa.Column('state', sa.String(length=120), nullable=True))
    op.add_column('Show', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.drop_column('Show', 'time')
    op.add_column('Venue', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Venue', 'ContactInfo', ['contact_id'], ['id'])
    op.drop_column('Venue', 'city')
    op.drop_column('Venue', 'state')
    op.drop_column('Venue', 'address')
    op.drop_column('Venue', 'phone')
    op.drop_column('Venue', 'facebook_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('facebook_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('address', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'contact_id')
    op.add_column('Show', sa.Column('time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('Show', 'start_time')
    op.drop_column('ContactInfo', 'state')
    op.drop_column('ContactInfo', 'phone')
    op.drop_column('ContactInfo', 'facebook_link')
    op.drop_column('ContactInfo', 'city')
    op.drop_column('ContactInfo', 'address')
    op.add_column('Artist', sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('facebook_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Artist', type_='foreignkey')
    op.drop_column('Artist', 'contact_id')
    # ### end Alembic commands ###
